-- Tabela de Usuários (Login)
CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    role VARCHAR(50)
);

-- Tabela de Ministérios
CREATE TABLE IF NOT EXISTS ministerios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    descricao TEXT,
    lider VARCHAR(255),
    pastor_responsavel VARCHAR(255),
    contato_lider VARCHAR(255),
    base VARCHAR(255)
);

-- Tabela de Voluntários
CREATE TABLE IF NOT EXISTS voluntarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_completo VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    telefone VARCHAR(255) NOT NULL,
    data_nascimento DATE NOT NULL,
    termos_aceitos BOOLEAN NOT NULL,
    data_criacao TIMESTAMP,

    -- Campos Administrativos
    data_termo DATE,
    proxima_renovacao DATE,
    status_termo VARCHAR(50),
    manual_entregue BOOLEAN DEFAULT FALSE,
    data_integracao DATE,
    lider_integracao VARCHAR(255)
);

-- Tabela de Antecedentes Criminais
CREATE TABLE IF NOT EXISTS antecedentes_criminais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voluntario_id BIGINT NOT NULL UNIQUE,
    caminho_arquivo_s3 VARCHAR(500),
    nome_original_arquivo VARCHAR(255),
    status VARCHAR(50),
    CONSTRAINT fk_voluntario_antecedentes FOREIGN KEY (voluntario_id) REFERENCES voluntarios(id)
);

-- Tabela de Ligação (Voluntário <-> Ministérios)
CREATE TABLE IF NOT EXISTS voluntario_ministerios (
    voluntario_id BIGINT NOT NULL,
    ministerio_id BIGINT NOT NULL,
    PRIMARY KEY (voluntario_id, ministerio_id),
    CONSTRAINT fk_vm_voluntario FOREIGN KEY (voluntario_id) REFERENCES voluntarios(id),
    CONSTRAINT fk_vm_ministerio FOREIGN KEY (ministerio_id) REFERENCES ministerios(id)
);

-- Inserir Admin Inicial (Se não existir)
INSERT INTO usuarios (login, senha, role)
SELECT 'admin', '$2a$10$G8.y/dI.q/e.t.y.u.i.o.p.A.s.d.f.G.h.j.k.l.', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM usuarios WHERE login = 'admin');
-- Nota: A senha hash acima é um exemplo, o seu código Java 'CriarAdminInicial' ainda funcionará.