-- 1. Adicionar CPF na tabela Voluntários
ALTER TABLE voluntarios ADD COLUMN cpf VARCHAR(14);

-- 2. Criar tabela de Bases Ministeriais (COM CAMPO LÍDER)
CREATE TABLE bases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL UNIQUE,
    lider VARCHAR(255)
);

-- 3. Alterar Ministérios para ter chave estrangeira para Base
ALTER TABLE ministerios ADD COLUMN base_id BIGINT;
ALTER TABLE ministerios ADD CONSTRAINT fk_ministerio_base FOREIGN KEY (base_id) REFERENCES bases(id);

-- 4. Migração de Dados (Transforma o texto antigo em ID na tabela nova)
-- Insere as bases únicas que já existem nos ministérios
INSERT INTO bases (nome)
SELECT DISTINCT base FROM ministerios WHERE base IS NOT NULL;

-- Atualiza a referência
UPDATE ministerios m
SET base_id = (SELECT b.id FROM bases b WHERE b.nome = m.base)
WHERE base IS NOT NULL;

-- 5. Remover a coluna antiga de texto
ALTER TABLE ministerios DROP COLUMN base;