-- Tabela de Espaços
CREATE TABLE IF NOT EXISTS espacos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    capacidade INTEGER,
    descricao TEXT
);

-- Tabela de Eventos (Série)
CREATE TABLE IF NOT EXISTS eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    descricao TEXT,
    ministerio_id BIGINT,
    is_recorrente BOOLEAN DEFAULT FALSE,
    regra_recorrencia VARCHAR(255),
    apoio_necessario TEXT,
    estimativa_participantes INTEGER,
    CONSTRAINT fk_evento_ministerio FOREIGN KEY (ministerio_id) REFERENCES ministerios(id)
);

-- Tabela de Ocorrências de Eventos (Instâncias no calendário)
CREATE TABLE IF NOT EXISTS evento_ocorrencias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id BIGINT NOT NULL,
    espaco_id BIGINT,
    data_inicio TIMESTAMP NOT NULL,
    data_fim TIMESTAMP NOT NULL,
    status VARCHAR(50) NOT NULL,
    observacao TEXT,
    CONSTRAINT fk_ocorrencia_evento FOREIGN KEY (evento_id) REFERENCES eventos(id) ON DELETE CASCADE,
    CONSTRAINT fk_ocorrencia_espaco FOREIGN KEY (espaco_id) REFERENCES espacos(id)
);
